### ISSUE TITLE
state_district_wise.json format update -> JSON array

### ISSUE THREAD

**Issue by ars75** [covid19india/api#42] opened 2020-03-30 17:31 UTC
I propose updating the JSON format to have a JSON array to make it simpler to parse it easily in a dynamic manner.

Current JSON format
```
{
	"Kerala": {
		"districtData": {
			"Thrissur": {
				"confirmed": 7,
				"lastupdatedtime": "",
				"delta": {
					"confirmed": 0
				}
			},
			"Alappuzha": {
				"confirmed": 2,
				"lastupdatedtime": "",
				"delta": {
					"confirmed": 0
				}
			}
		}
	},
	"Maharashtra": {
		"districtData": {
			"Pune": {
				"confirmed": 42,
				"lastupdatedtime": "",
				"delta": {
					"confirmed": 5
				}
			},
			"Mumbai": {
				"confirmed": 75,
				"lastupdatedtime": "",
				"delta": {
					"confirmed": 3
				}
			}
		}
	},
	"Unknown": {
		"districtData": {
			"Unknown": {
				"confirmed": 284,
				"lastupdatedtime": "",
				"delta": {
					"confirmed": 0
				}
			}
		}
	}
}
```

Proposed JSON format
```
{
	"districtWise": [
		{
			"state": "Maharashtra",
			"districtData": [
				{
					"districtName": "Pune",
					"confirmed": 42,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 5
					}
				},
				{
					"districtName": "Mumbai",
					"confirmed": 75,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 3
					}
				}
			]
		},
		{
			"state": "Kerala",
			"districtData": [
				{
					"districtName": "Thrissur",
					"confirmed": 7,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 0
					}
				},
				{
					"districtName": "Alappuzha",
					"confirmed": 2,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 0
					}
				}
			]
		},
		{
			"state": "Unknown",
			"districtData": [
				{
					"districtName": "Unknown",
					"confirmed": 284,
					"lastupdatedtime": "",
					"delta": {
					  "confirmed": 0
					}
				}
			]
		}
	]
}
```

**Comment by strikertanmay** [comment] 2020-03-30 18:38
Yes, this formatting will make things simpler. I would like to work on this issue.

**Comment by krishnasen2401** [comment] 2020-03-31 07:48
Even tools like tableau and power bi have tough time in processing the current json format every district is take a single row and as result a matrix had been formed

**Comment by ars75** [comment] 2020-04-01 01:18
Yep and even for programs that need this data, as new states and districts are being added its becoming difficult to keep up because of the non dynamic nature of this JSON! I would really appreciate if this can be converted into the suggested dynamic JSON array ASAP.

**Comment by krishnasen2401** [comment] 2020-04-01 06:38
until someone gets assigned it difficult to get it noticed

**Comment by sumitmckv** [comment] 2020-04-01 08:00
@ars75 @krishnasen2401 I would suggest creating a new state_district_wise_v2.json with the proposed JSON format from state_district_wise.json.
And keep exiting format as it is in state_district_wise.json otherwise it's going to break existing applications that are using this JSON.
@JunaidBabu your thoughts

**Comment by krishnasen2401** [comment] 2020-04-01 08:06
The problem is that state and remain heading are taken as column heading or in matrix format states as one column and remain data as seperate column i.e each district as seperate column as result the data has 20 rows but dynamic column count create or only 1 row with dynamic number of  column
So We were suggesting a api format

**Comment by sumitmckv** [comment] 2020-04-01 08:22
Yes, I agree with the restructuring.
Better to have a new API for this restructuring instead of changing the existing one.
Something like:
https://api.covid19india.org/state_district_wise_v2.json
Or
https://api.covid19india.org/v2/state_district_wise.json

And keep the existing format as it is in https://api.covid19india.org/state_district_wise.json

**Comment by krishnasen2401** [comment] 2020-04-01 08:41
That would help everyone

**Comment by JunaidBabu** [comment] 2020-04-01 09:59
Sounds good.. please raise a PR.
Let's maybe keep it like https://api.covid19india.org/v2/state_district_wise.json

**Comment by sumitmckv** [comment] 2020-04-01 10:47
@JunaidBabu I will work on this today.

**Closed** 2020-04-02 03:43 UTC
Labels: enhancement, help wanted

**Comment by krishnasen2401** [comment] 2020-04-02 03:47
Thank you
