### ISSUE TITLE
[MAJOR] issue(s) with raw_data3.json

### ISSUE THREAD

**Issue by parshnt** [covid19india/api#187] opened 2020-04-29 22:07 UTC
I've noticed some problems with [raw_data3.json](https://api.covid19india.org/states_daily.json) :

1. In the “numcases” field, which mentions the number of cases in that district. there are negative values in some cases. (I'm genuinely confused if it's a feature or bug!)
	>   for entryid(s) : 938, 1021, 1367

2. According to  [raw_data3.json](https://api.covid19india.org/states_daily.json), the confirmed cases in last 3 days (27, 28 & 29) add up-to (adding values of “numcases” field)  a total  of **7392** Vs **5172** in [data.json](https://api.covid19india.org/data.json)

my bad, if I misunderstood the new API or if it's an Irrelevant Issue.

**Comment by sudevschiz** [comment] 2020-04-30 09:02
-ve values are a feature. This happens when states reduce a patient from one district and (we guess, ) add to a different district. We are trying structurally capture what is happening in state bulletins. 

Regarding the total cases : Did you filter only 27,28,29 AND Current Status = "Hospitalized". I am getting the 5173 (+1 because we added on case to yesterday after you posted this issue) value.

![image](https://user-images.githubusercontent.com/4298868/80692576-b9b90400-8b0c-11ea-86e7-4a9a9f7023e4.png)

**Comment by parshnt** [comment] 2020-04-30 09:15
Thanks, I wasn't aware of the -ve values.

Regarding the total cases: Yes, I filtered only 27, 28, 29, but NOT Current Statues = "Hospitalized". I was treating it like the old API where each entry = new confirmed case.

and according to my understanding (correct me if I'm wrong) with the new API, all three (confirmed/hospitalized, deceased & recovered) are unified into one API?

**Comment by sudevschiz** [comment] 2020-05-02 00:23
Yes. In raw_data3, confirmed, deceased and recovered all entered in the same sheet.

**Comment by sudevschiz** [comment] 2020-05-02 01:09
Closing this issue. If there are more questions regarding the format of raw_data3. Please use this thread : https://github.com/covid19india/api/issues/195

**Closed by sudevschiz** 2020-05-02 01:09 UTC

**Comment by parshnt** [comment] 2020-05-02 10:44
Thanks a lot! 
It all makes sense now!
