### ISSUE TITLE
'totaltested' count for prior date greater than posterior date for 'State Level : Testing data'

### ISSUE THREAD

**Issue by pratikdk** [covid19india/api#242] opened 2020-05-17 08:25 UTC
I was trying to plot state level **daily testing count** by retrieving using 'State Level : Testing data'. But observed a discrepancy in the **'totaltested'** count where its prior count is greater than post which shouldn't be the case right (total should always increase), For example: If I retrieve and plot for Maharashtra, this is what I observed.

![state_level_negative](https://user-images.githubusercontent.com/20542313/82139357-d6f80d00-9844-11ea-9b90-865879bdcc13.png)
![state_level_negative1](https://user-images.githubusercontent.com/20542313/82139359-dbbcc100-9844-11ea-8f6f-edd5f4530878.png)
![state_level_negative2](https://user-images.githubusercontent.com/20542313/82139360-deb7b180-9844-11ea-8e50-99cff910a842.png)

**Comment by sudevschiz** [comment] 2020-05-17 08:53
Yep. This happened because the MH bulletin reported a lower count than previous day in their bulletin. We are not sure why it happened, just reflecting the information that was present in the bulletin

**Comment by bee-rickey** [comment] 2020-05-17 10:00
Closing the bug as this is not a bug on the coding/data side. A bug with the state govt. Can't assign to them :(

**Closed by bee-rickey** 2020-05-17 10:00 UTC
