### ISSUE TITLE
API not showing correct data

### ISSUE THREAD

**Issue by Abhinav1101** [covid19india/api#387] opened 2020-07-08 07:48 UTC
https://api.covid19india.org/state_district_wise.json  This api is showing 'delta' for almost all district to be 0 but certainly this is not the case. What is the issue ? Look for it.

**Comment by sudevschiz** [comment] 2020-07-08 16:23
delta represents the new cases for today. As bulletins are released in the evening through night, the delta values will get populated.

**Comment by Abhinav1101** [comment] 2020-07-09 15:56
Okay thanks, but with this api there is one issue that it is taking so long to fetch data in spite of having good internet connection. Can you tell me what may be the reason? Is it because data is large or any other issue.

**Comment by bee-rickey** [comment] 2020-07-10 09:32
@Abhinav1101 works fine here. Not sure what the issue is with fetching.

**Closed** 2020-07-15 21:28 UTC
